webnginx:
  image: 'bonjourausy_webnginx:latest'
  links:
    - php
  ports:
    - '8080:8080'
  volumes_from:
    - php
mysql:
  environment:
    - MYSQL_DATABASE=bonjourausy
    - MYSQL_ROOT_PASSWORD=admin
  image: 'bonjourausy_mysql:latest'
  volumes:
    - /var/lib/mysql
php:
  image: 'bonjourausy_server:latest'
  links:
    - mysql
  volumes:
    - ./images/server/src/public:/var/www/html

